// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApt5B-hjghHJja3660HYVvL1yjkVizlBg',
    appId: '1:459219224817:web:fa100b420d1b48ab7f4150',
    messagingSenderId: '459219224817',
    projectId: 'flutter-1e405',
    authDomain: 'flutter-1e405.firebaseapp.com',
    storageBucket: 'flutter-1e405.appspot.com',
    measurementId: 'G-J08ZC7DTG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjVRoUdxXuta76qsJD_ZUeFtQowOs8Nk',
    appId: '1:459219224817:android:38f9f2a3d631f6b77f4150',
    messagingSenderId: '459219224817',
    projectId: 'flutter-1e405',
    storageBucket: 'flutter-1e405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPpu77WSrpj6pKeHIla18nsBMMXc1d-gs',
    appId: '1:459219224817:ios:1892669e4f98a3ef7f4150',
    messagingSenderId: '459219224817',
    projectId: 'flutter-1e405',
    storageBucket: 'flutter-1e405.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPpu77WSrpj6pKeHIla18nsBMMXc1d-gs',
    appId: '1:459219224817:ios:1892669e4f98a3ef7f4150',
    messagingSenderId: '459219224817',
    projectId: 'flutter-1e405',
    storageBucket: 'flutter-1e405.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
